name: Continuous Deployment
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd sspwa && yarn install --immutable --immutable-cache --check-cache && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUCKDAPP }}'
          channelId: live
          projectId: luckdapp
          entryPoint: "./sspwa"
